### PR TITLE
- add a paragraph to mention recast usage

### PR DESCRIPTION
**Pull request by wenq1**
ref #129

### CODE REVIEW

**Comment by coderaiser** [comment]
I don't really like formulating, there is 1000000 cases when output can be screwed, and the same go's to ESlint, Babel and JSCodeshift, so when you have any issues with formatting it's definitely Recast, and you can create issues to them. This is amazing tool, but the problem much harder than you think.

**Comment by wenq1** [comment]
you can always rephrase it. Not mentioning anywhere in the doc that issues should be filed elsewhere (e.g. to the recast project) is somewhat strange though.

**Comment by coderaiser** [comment]
https://github.com/coderaiser/putout#operator

**Comment by coderaiser** [comment]
Also broken formatting it's not really an issue if ESLint can fix that, there is line about that https://github.com/coderaiser/putout#-integration-with-eslint and [bunch of ESLint rules](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#formatting) with autofixes.

**Pull request closed without merging**
