### PR TITLE
fix(putout) make defaultOpts use .putout.json

### PR DESCRIPTION
**Pull request by hntrl**
putout(source, require('../.putout.json')) works great, but could be better.

### CODE REVIEW

**Comment by coderaiser** [comment]
Thank you, that's interesting idea :). The only problem is `putout` should have ability to be used in a browser (https://github.com/fkling/astexplorer/pull/414).

Could you please tell me why do you need this? Maybe we can make things work in another other way. For example, you trying to read current directory only, but [cli-version](https://github.com/coderaiser/putout/blob/v4.32.0/packages/putout/bin/putout.js#L231-L256) search current directory and up till it finds `.putout.json`, if can't it search of a `package.json`.

What we can do, is move out `getOptions` into `lib/getOptions`. And add it to `putout`. So your code will looks like this:

```js
const putout = require('putout');
const {readOptions} = putout;

putout(source, readOptions());
```

This will help to:
- simplify `cli` version, 
- avoid duplication,
- test this code

What do you think about it?

**Comment by hntrl** [comment]
This shouldn't conflict with the cli since all we're doing here is setting the default object of options.
The cli works great, i'd just expect that the default options in the API be the .putout.json in the root of the project. If not there then it should at least be documented [here](https://github.com/coderaiser/putout/blob/master/README.md#API). ( had some trouble the first time I was using the api (: )

**Comment by hntrl** [comment]
heh. thought this would be an easy add. I'll make it a little bit more robust

**Comment by coderaiser** [comment]
Look, this breaks tests, duplicate logic, and makes harder to support the core engine :). What I can suggest you is such API, if you need this:

```js
const putout = require('putout');
const {readOptions} = putout;

putout(source, readOptions());
```

When `putout` used as a library it shouldn't read any configuration files without direct call. This is what `readOptions` can provide, and what we can add to documentation.

This improves quality of a code base, adds ability to test `readOptions` function in a normal way and simplifies `cli` engine.

Your solution is a pure duplication of [getOptions](https://github.com/coderaiser/putout/blob/v4.32.0/packages/putout/bin/putout.js#L231-L256) implemented in cli which is not handle all the cases.

**Comment by hntrl** [comment]
ah, I see. Looks like I was just misunderstanding you before. Sorry about that! 😅

**Comment by coderaiser** [comment]
Could you please tell me how do you use `putout`? Maybe what you need is some kind of `defaultOptions` with all rules enabled by default similar to the way cli version works?

It can be something like:

```js
const putout = require('putout');
const {getDefaultOptions} = putout;

putout(source, getDefaultOptions());
```

So you wan't need `.putout.json`. What kind of rules are you disable?

**Comment by hntrl** [comment]
I use putout to remove code that isn't relevant to a build. I take out a function using regex, then loop putout until all the unused variables are removed. I don't necessarily need everything else, just the `remove-unused-vars` rule. 

The only reason for this PR was when I was trying to implement with the API, I was confused why the results were always blank. It seems to be documented now so all is well.

Sidenote: it would make sense to have .putout always in the root of the project. `.babelrc` `rollup.config.js` `.eslintrc.json` all reside there, so why shouldn't putout? If I have a putout file in some other directory, i'd just provide an arg. (`-c /path/to/.putout.json`)

**Pull request closed without merging**
